### ISSUE TITLE
Footer items not update

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/nomos.tech#10]
- [ ] Temrs & conditions should be linked to `/terms`
- [ ] type in `Temrs & conditions`. should be `Terms & conditions`
- [ ] We do not have policy page so we can remove `Privacy policy`

**Comment by jinhojang6** [comment]
Fixed at https://github.com/acid-info/nomos.tech/commit/a9605f3dd818a6222d894149841c349bf6c8af43
